### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './img_encoder.pkl'

### ISSUE THREAD

**Issue by AndrewZion** [LiqiangJing/Vision-GPLM#1]
train 62000 valid 2000 test 2000
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    model = MultiModal_BART(config)
  File "/home/xlb/code_work/multimodal_summarization/Vision-GPLM-main/fine-tuning/models.py", line 67, in __init__
    self.img_encoder = torch.load("./img_encoder.pkl")
  File "/home/xlb/.conda/envs/py36_env/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xlb/.conda/envs/py36_env/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xlb/.conda/envs/py36_env/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './img_encoder.pkl'

Hello, in the fine-tuning training phase, in the file models.py, self.img_encoder = torch.load("./img_encoder.pkl"), I did not find the img_encoder.pkl file. After post-training training, I did not find the saved img_encoder.pkl file.

**Comment by LiqiangJing** [comment]
HI,

I will check that but I am not sure that I can find the original code. Because so much time has passed, the code for this project may have been deleted

If you are interested in the multimodal generation, you can also read our other paper:
V2P: Vision-to-Prompt based Multi-Modal Product Summary Generation
Adapting Generative Pretrained Language Model for Open-domain Multimodal Sentence Summarization.
Multi-source Semantic Graph-based Multimodal Sarcasm Explanation Generation.

**Comment by LiqiangJing** [comment]
For the img_encoder.pkl, we downloaded it from timm package.
